import React, { Component } from 'react';
import "../scss/main.scss";

class Widget extends Component {
  render() {
    return (
      <div className="widget">
        <p>Content generated by a React widget!</p>
      </div>
    );
  }
}

export default Widget;
